import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Copy, Download, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { AnalysisResult } from '@/context/AppContext';

interface RadiologistReportProps {
  analysisResult: AnalysisResult;
}

const RadiologistReport: React.FC<RadiologistReportProps> = ({ analysisResult }) => {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const generateReport = (): string => {
    const timestamp = new Date(analysisResult.analysisTimestamp).toLocaleString();
    
    return `
CHEST X-RAY ANALYSIS REPORT
============================
Patient ID: ${analysisResult.patientId}
Analysis Date: ${timestamp}
AI Classification: ${analysisResult.classification}
Confidence: ${analysisResult.confidence}%

FINDINGS:
---------
${analysisResult.noduleLocation}
${analysisResult.noduleDimensions}

${analysisResult.findings.length > 0 
  ? analysisResult.findings.map(f => `• ${f}`).join('\n')
  : '• No significant abnormalities detected'}

ADDITIONAL OBSERVATIONS:
------------------------
${analysisResult.additionalObservations.map(o => `• ${o}`).join('\n')}

IMPRESSION:
-----------
${analysisResult.riskLevel} risk assessment (Score: ${analysisResult.riskScore}%)
${analysisResult.detailedReport || `The chest radiograph demonstrates ${analysisResult.classification.toLowerCase()} findings. ${analysisResult.findings.length > 0 ? 'Areas of concern have been identified and require clinical correlation.' : 'No acute cardiopulmonary abnormalities identified.'}`}

DIFFERENTIAL DIAGNOSIS:
-----------------------
${analysisResult.classification === 'Normal' 
  ? '• Normal chest radiograph\n• No differential diagnosis warranted'
  : `• Pulmonary nodule (primary consideration)
• Benign granuloma
• Inflammatory process
• Requires correlation with clinical history and prior imaging`}

RECOMMENDATION:
---------------
${analysisResult.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

DISCLAIMER:
-----------
This AI-generated analysis is for investigational purposes only. All findings must be verified by a qualified radiologist or pulmonologist before any clinical decisions are made. This report does not constitute a medical diagnosis.

============================
Generated by LungScan AI
Model: DenseNet121-based Analysis
`.trim();
  };

  const handleCopy = async () => {
    const report = generateReport();
    await navigator.clipboard.writeText(report);
    setCopied(true);
    toast({
      title: "Copied",
      description: "Report copied to clipboard"
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const report = generateReport();
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `chest-xray-report-${analysisResult.patientId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast({
      title: "Downloaded",
      description: "Report saved as text file"
    });
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-card rounded-2xl shadow-sm border border-border overflow-hidden"
    >
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full p-6 flex items-center justify-between hover:bg-muted/50 transition-colors"
      >
        <div className="flex items-center gap-3">
          <FileText className="w-5 h-5 text-primary" />
          <h2 className="text-xl font-semibold">Professional Radiologist Report</h2>
        </div>
        <motion.span
          animate={{ rotate: expanded ? 180 : 0 }}
          className="text-muted-foreground"
        >
          ▼
        </motion.span>
      </button>

      <motion.div
        initial={false}
        animate={{ height: expanded ? 'auto' : 0 }}
        className="overflow-hidden"
      >
        <div className="px-6 pb-6">
          <div className="flex gap-2 mb-4">
            <Button size="sm" variant="outline" onClick={handleCopy}>
              {copied ? (
                <>
                  <CheckCircle2 className="w-4 h-4 mr-1 text-success" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 mr-1" />
                  Copy to Clipboard
                </>
              )}
            </Button>
            <Button size="sm" variant="outline" onClick={handleDownload}>
              <Download className="w-4 h-4 mr-1" />
              Save as .txt
            </Button>
          </div>

          <pre className="bg-muted rounded-lg p-4 text-sm font-mono whitespace-pre-wrap overflow-x-auto max-h-96 overflow-y-auto">
            {generateReport()}
          </pre>
        </div>
      </motion.div>
    </motion.div>
  );
};

export default RadiologistReport;
